"""initial schema

Revision ID: a98818f7f8b2
Revises: 
Create Date: 2026-09-07 12:41:12.297255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a98818f7f8b2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('OFFICIAL', 'RESEARCH', 'COMMUNITY', 'MEDIA', name='sourcetype', native_enum=False), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('feed_url', sa.String(length=1024), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('collection_method', sa.Enum('RSS', 'ATOM', 'API', 'GITHUB', 'HTML', 'OTHER', name='collectionmethod', native_enum=False), nullable=False),
    sa.Column('category_hint', sa.String(length=64), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_user_id'), 'users', ['telegram_user_id'], unique=True)
    op.create_table('digest_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('digest_date', sa.Date(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('SENT', 'FAILED', name='digeststatus', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_digest_deliveries_digest_date'), 'digest_deliveries', ['digest_date'], unique=False)
    op.create_index(op.f('ix_digest_deliveries_user_id'), 'digest_deliveries', ['user_id'], unique=False)
    op.create_table('news_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('why_it_matters', sa.Text(), nullable=False),
    sa.Column('practical_use', sa.Text(), nullable=False),
    sa.Column('risks', sa.JSON(), nullable=False),
    sa.Column('recommendation', sa.Enum('TEST', 'WATCH', 'SKIP', name='recommendation', native_enum=False), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('novelty_score', sa.Integer(), nullable=False),
    sa.Column('practical_value_score', sa.Integer(), nullable=False),
    sa.Column('technical_significance_score', sa.Integer(), nullable=False),
    sa.Column('enterprise_relevance_score', sa.Integer(), nullable=False),
    sa.Column('personal_relevance_score', sa.Integer(), nullable=False),
    sa.Column('source_reliability_score', sa.Integer(), nullable=False),
    sa.Column('stt_relevance', sa.Integer(), nullable=False),
    sa.Column('meeting_relevance', sa.Integer(), nullable=False),
    sa.Column('rag_relevance', sa.Integer(), nullable=False),
    sa.Column('agent_relevance', sa.Integer(), nullable=False),
    sa.Column('coding_relevance', sa.Integer(), nullable=False),
    sa.Column('on_prem_relevance', sa.Integer(), nullable=False),
    sa.Column('estimated_test_effort', sa.String(length=32), nullable=True),
    sa.Column('suggested_test', sa.Text(), nullable=True),
    sa.Column('primary_url', sa.String(length=2048), nullable=False),
    sa.Column('primary_source', sa.String(length=255), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['news_clusters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id')
    )
    op.create_table('raw_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_priority', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('canonical_url', sa.String(length=2048), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('raw_html', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'EXTRACTED', 'DUPLICATE', 'FILTERED', 'QUEUED_FOR_AI', 'PROCESSED', 'FAILED', name='processingstatus', native_enum=False), nullable=False),
    sa.Column('failure_reason', sa.String(length=1024), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['news_clusters.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_items_canonical_url'), 'raw_items', ['canonical_url'], unique=False)
    op.create_index(op.f('ix_raw_items_cluster_id'), 'raw_items', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_raw_items_content_hash'), 'raw_items', ['content_hash'], unique=False)
    op.create_index(op.f('ix_raw_items_source_id'), 'raw_items', ['source_id'], unique=False)
    op.create_index(op.f('ix_raw_items_status'), 'raw_items', ['status'], unique=False)
    op.create_table('news_item_category_links',
    sa.Column('news_item_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('LLM_MODELS', 'PROGRAMMING', 'STT', 'MEETING_INTELLIGENCE', 'DOCUMENTS_RAG', 'AI_AGENTS', 'ENTERPRISE_AI', 'MULTIMEDIA', 'OTHER', name='category', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['news_item_id'], ['news_items.id'], ),
    sa.PrimaryKeyConstraint('news_item_id', 'category')
    )
    op.create_table('related_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_item_id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['news_item_id'], ['news_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_related_sources_news_item_id'), 'related_sources', ['news_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_related_sources_news_item_id'), table_name='related_sources')
    op.drop_table('related_sources')
    op.drop_table('news_item_category_links')
    op.drop_index(op.f('ix_raw_items_status'), table_name='raw_items')
    op.drop_index(op.f('ix_raw_items_source_id'), table_name='raw_items')
    op.drop_index(op.f('ix_raw_items_content_hash'), table_name='raw_items')
    op.drop_index(op.f('ix_raw_items_cluster_id'), table_name='raw_items')
    op.drop_index(op.f('ix_raw_items_canonical_url'), table_name='raw_items')
    op.drop_table('raw_items')
    op.drop_table('news_items')
    op.drop_index(op.f('ix_digest_deliveries_user_id'), table_name='digest_deliveries')
    op.drop_index(op.f('ix_digest_deliveries_digest_date'), table_name='digest_deliveries')
    op.drop_table('digest_deliveries')
    op.drop_index(op.f('ix_users_telegram_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('sources')
    op.drop_table('news_clusters')
    # ### end Alembic commands ###
